services:
  go:
    image: cosmtrek/air
    working_dir: /app
    env_file:
      - .env
    environment:
      air_wd: "/app"
    volumes:
      - ./:/app
    ports:
      - ${WEB_PORT:-8080}:80
    restart: unless-stopped
